In [ ]:
help()

In [2]:
import cntext as ct

glove_file = '三体_vectors.txt'
word2vec_file = '三体_vectors_word2vec.txt'

wv = ct.glove2word2vec(glove_file, word2vec_file)
wv

Converting GloVe model to Word2Vec format...
Finish! The word2vec model has been saved to 三体_vectors_word2vec.txt.


In [38]:
wv.vector_size

50

In [1]:
import cntext as ct

help(ct.semantic_centroid)

Help on function semantic_centroid in module cntext.mind:

semantic_centroid(wv, words)
    计算多个词语的语义中心向量

    Args:
        wv (gensim.models.keyedvectors.KeyedVectors): 词向量模型
        words (list): 词语列表

    Returns:
        np.array: 语义中心向量



In [5]:
male_vector = ct.semantic_centroid(wv=wv, words=['他', '爸爸', '父亲'])
male_vector

array([-0.67194201, -0.09716467,  0.37204367, -0.26802333,  0.44919133,
       -0.55783835,  0.233331  , -0.31449966, -0.01175333,  0.861106  ,
       -0.18059967,  0.26889534, -0.65725034,  0.37752367, -0.39446167,
        0.25732133, -0.44991867, -0.20689067,  0.24654933, -0.10600067,
        0.26759601, -0.54749368, -0.29525267, -0.125299  ,  0.03948133,
       -0.63043936, -0.14658167,  0.091333  , -0.390507  , -0.038167  ,
       -0.35712768, -0.360632  , -0.01879468, -0.43197834,  0.47045965,
       -0.16900699, -0.000953  , -0.26595834, -0.09124767, -0.00964567,
       -0.21009666,  0.30321334,  0.03758934, -0.11087868,  0.128426  ,
        0.32476601, -0.31724467,  0.03618633, -0.55504032, -0.01727767])

In [7]:
wv.similar_by_vector(male_vector)

[('他', 0.9414033889770508),
 ('罗辑', 0.7558885216712952),
 ('父亲', 0.7336329817771912),
 ('她', 0.7221807837486267),
 ('自己', 0.6953485608100891),
 ('心中', 0.6771865487098694),
 ('汪淼', 0.6702131628990173),
 ('年轻人', 0.6379985213279724),
 ('似乎', 0.6350806355476379),
 ('大史', 0.632330596446991)]

In [24]:
santi_vector = ct.semantic_centroid(wv=wv, words=['三体', '游戏', '文明'])
santi_vector


array([ 0.50100301,  0.47088166,  0.62678533,  0.467761  , -0.45723801,
        0.14383099, -0.891913  ,  0.21665466, -0.25624666,  0.75139199,
        0.24235734, -0.96731635,  0.18584933,  0.02404067,  0.37241099,
        0.14754967, -0.69784865,  0.328805  ,  0.50277534, -0.60690465,
       -0.37693266, -0.49491167,  0.57581334, -0.77428068,  0.49858767,
       -0.72862932, -0.08807833, -0.01593066, -0.48299166,  0.187245  ,
       -0.40747799, -0.90307034, -0.22071966, -0.074589  , -0.02041567,
       -0.20742667,  0.887746  , -0.21263001, -0.023177  , -0.64816999,
        1.02768135,  0.256734  ,  0.619848  , -1.25406067,  0.68969666,
        0.852735  ,  0.08151634,  0.21651132,  0.25295466, -0.648615  ])

In [25]:
wv.get_vector('降临')

array([ 0.577487, -0.060531,  0.356737,  0.193957, -0.292358, -0.165449,
       -0.661044,  0.157345, -0.2359  ,  0.212128,  0.504738, -0.179831,
       -0.176003, -0.295074,  0.322727,  0.053681, -0.251957,  0.860062,
        0.879374, -0.40674 , -0.191434, -1.052616,  0.087331, -0.221943,
        0.192871,  0.023422, -0.723445, -0.342288, -0.223812, -0.416643,
       -0.356476, -0.291126,  0.011684, -0.321453, -0.399773,  0.086929,
        0.401904,  0.45351 , -0.529592,  0.186929,  0.05578 ,  0.145299,
       -0.075225, -0.712731,  0.505974,  0.494117,  0.281392,  1.229976,
        1.291117,  0.107688], dtype=float32)

In [34]:
santi_vector = ct.semantic_centroid(wv=wv, words=['三体', '降临', '组织', '拯救'])
print(santi_vector)
wv.similar_by_vector(santi_vector, topn=10)

[ 0.6267875   0.08975425  0.48438451  0.405128   -0.49928901  0.11347825
 -0.90057975  0.11877625 -0.27053049  0.344603    0.4368495  -0.3839495
  0.02633176 -0.138534    0.2531555  -0.0060905  -0.48776849  0.75548999
  0.72575876 -0.446079   -0.30361701 -1.039792    0.457687   -0.4286315
  0.44577325 -0.39119426 -0.4783935  -0.2596135  -0.32513325 -0.10315975
 -0.42880575 -0.48328425  0.129438   -0.17085625 -0.13454625 -0.070053
  0.68060375  0.16736924 -0.15664874 -0.20528575  0.385481    0.206432
  0.18913225 -0.93453825  0.58597099  0.60727924  0.009064    0.87661726
  0.65814423 -0.356567  ]


[('降临', 0.8707027435302734),
 ('组织', 0.8625670671463013),
 ('三体', 0.8621653914451599),
 ('派', 0.8343338966369629),
 ('拯救', 0.8301094174385071),
 ('叛军', 0.784512460231781),
 ('地球', 0.7536635398864746),
 ('世界', 0.7245718836784363),
 ('外部', 0.7078365087509155),
 ('入侵', 0.6962169408798218)]

In [31]:
wv.similar_by_word('降临', topn=10)

[('派', 0.9606220126152039),
 ('拯救', 0.8047293424606323),
 ('组织', 0.7054259181022644),
 ('截留', 0.6824786067008972),
 ('统帅', 0.6796982884407043),
 ('入侵', 0.6169854402542114),
 ('时前', 0.6167060732841492),
 ('叛军', 0.6111961007118225),
 ('文化', 0.5985738039016724),
 ('时后', 0.5929005742073059)]

In [13]:
wv.similar_by_key('三体')

[('叛军', 0.7699569463729858),
 ('更新', 0.7687217593193054),
 ('地球', 0.760529100894928),
 ('全集', 0.7575182914733887),
 ('最快', 0.7426372170448303),
 ('世界', 0.7262137532234192),
 ('最新', 0.7219281792640686),
 ('游戏', 0.7180070877075195),
 ('危机', 0.7020451426506042),
 ('教', 0.7012627720832825)]

In [22]:

print(f'词表有 {len(wv_model.key_to_index)} 个词')
print(f'向量是 {wv_model.vector_size} 维')

词表有 4365 个词
向量是 50 维


In [23]:
wv_model.key_to_index

{'的': 0,
 '了': 1,
 '在': 2,
 '是': 3,
 '他': 4,
 '我': 5,
 '你': 6,
 '说': 7,
 '这': 8,
 '中': 9,
 '和': 10,
 '一个': 11,
 '上': 12,
 '都': 13,
 '有': 14,
 '也': 15,
 '她': 16,
 '但': 17,
 '就': 18,
 '着': 19,
 '不': 20,
 '对': 21,
 '人': 22,
 '那': 23,
 '没有': 24,
 '我们': 25,
 '很': 26,
 '到': 27,
 '他们': 28,
 '地': 29,
 '汪淼': 30,
 '自己': 31,
 '什么': 32,
 '这个': 33,
 '它': 34,
 '罗辑': 35,
 '三体': 36,
 '把': 37,
 '您': 38,
 '现在': 39,
 '知道': 40,
 '像': 41,
 '被': 42,
 '从': 43,
 '吗': 44,
 '与': 45,
 '后': 46,
 '将': 47,
 '已经': 48,
 '要': 49,
 '可能': 50,
 '看到': 51,
 '就是': 52,
 '世界': 53,
 '叶文洁': 54,
 '吧': 55,
 '又': 56,
 '能': 57,
 '太阳': 58,
 '还': 59,
 '这样': 60,
 '人类': 61,
 '想': 62,
 '不是': 63,
 '可以': 64,
 '看': 65,
 '过': 66,
 '时': 67,
 '这种': 68,
 '你们': 69,
 '文明': 70,
 '地球': 71,
 '去': 72,
 '来': 73,
 '让': 74,
 '用': 75,
 '面壁': 76,
 '宇宙': 77,
 '那个': 78,
 '只是': 79,
 '向': 80,
 '起来': 81,
 '走': 82,
 '太空': 83,
 '为': 84,
 '者': 85,
 '会': 86,
 '更': 87,
 '出现': 88,
 '大': 89,
 '这里': 90,
 '最': 91,
 '下': 92,
 '最后': 93,
 '呢': 94,
 '好': 95,
 '如果': 96,
 '

In [29]:
print(wv_model.get_vector('她'))

[-0.956548  0.125269  0.723213  0.405499  0.066581 -0.809612 -1.274535
 -0.764035 -0.643188  0.288232  0.788974  0.579577 -0.735807 -1.345063
  0.466422 -0.772552 -0.901493  1.054358 -0.907754  0.539987 -0.296221
 -0.119365 -1.01706  -1.173492 -0.727401  0.831272  0.192573 -0.535456
 -0.484225  0.410255  0.687898  0.827605 -0.201254 -0.096779 -1.555103
  0.73312  -0.063381 -0.664183 -1.586201  1.8531    0.407269  0.466495
  0.395166  0.175627  0.05807   0.105145 -0.057145  0.18848  -1.3395
  0.178473]


In [30]:
print(wv_model.get_vector('他'))

[-0.789099  0.092597  1.505065  0.875499  0.816217 -1.133284 -0.450952
  0.230626 -0.690256 -0.230622 -0.046771 -0.185922 -0.352591 -0.697114
 -0.88515  -1.333211 -0.210095  0.860029 -0.429213  0.573181  0.438712
 -1.567735  0.305492 -1.385258 -0.30028   0.980831 -0.49874  -0.667406
 -0.080418 -0.315143  0.589321 -0.239293 -0.236655  0.978831 -1.36892
  0.991611 -0.702171 -0.594096 -0.417828  1.18266   0.328675  0.666896
 -0.034706  1.467876 -0.54826   0.832025 -0.302658  0.976208 -0.89486
  0.398276]


In [31]:
help(ct.semantic_centroid)

Help on function semantic_centroid in module cntext.mind:

semantic_centroid(wv, words)
    calculate the semantic centroid vector of multiple word vectors
    :param wv: gensim.word2vec.Word2Vector
    :param words: word list
    :return:



In [33]:
!ls

三体_cooccurrence.bin        三体_vectors_word2vec.txt
三体_cooccurrence.shuf.bin   三体_vocab.txt
三体_vectors.bin             未命名.ipynb
三体_vectors.txt


In [34]:
ct.load_w2v(w2v_path = '三体_cooccurrence.bin')

Loading word2vec model bin file...


UnpicklingError: invalid load key, '\x01'.

In [27]:
help(wv_model.similar_by_word)

Help on method similar_by_word in module gensim.models.keyedvectors:

similar_by_word(word, topn=10, restrict_vocab=None) method of gensim.models.keyedvectors.KeyedVectors instance
    Compatibility alias for similar_by_key().

